/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef BEAMASYM
#define BEAMASYM

#include "RooAbsPdf.h"
#include "RooHSEventsPDF.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
 
class BeamAsym : public RooHSEventsPDF {
public:
  BeamAsym() {} ; 
  BeamAsym(const char *name, const char *title,
	      RooAbsReal& _phiSigma,
	      RooAbsReal& _pol,
	      RooAbsCategory& _polState,
	      RooAbsReal& _beamAsym);
  BeamAsym(const BeamAsym& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new BeamAsym(*this,newname); }
  inline virtual ~BeamAsym() { }

protected:

  RooRealProxy phiSigma ;
  RooRealProxy pol ;
  RooCategoryProxy polState ;
  RooRealProxy beamAsym ;
  
  Double_t evaluate() const ;
  Double_t evaluateMC(const vector<Float_t> *vars,const  vector<Int_t> *cats) const ;
  void MakeSets();

private:

  ClassDef(BeamAsym,1) // Your description goes here...
};
 
#endif
